[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.14.0"
  EMAIL_CC = "bourseaujenny@live.fr"
  EMAIL_BCC = "charlie.piedferre@gmail.com"
  SMTP_FROM = "nepasrepondre@mcommemedoc.fr"
  SMTP_HOST = "smtp.hostinger.com"
  SMTP_PASS = "!Mcommemedoc/(12)"
  SMTP_PORT = "465"
  SMTP_SECURE = "true"
  SMTP_USER = "direction@mcommemedoc.fr"
  NITRO_PRERENDER_ROUTES = "/, /discovery, /fondements, /implication, /mission, /projects, /timeline, /contact"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NODE_ENV = "production"

