[build]
  command = "node --max-old-space-size=4096 ./node_modules/.bin/nuxt build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "20.11.0"
  NODE_ENV = "production"
  EMAIL_CC = "bourseaujenny@live.fr"
  EMAIL_BCC = "charlie.piedferre@gmail.com"
  SMTP_FROM = "nepasrepondre@mcommemedoc.fr"
  SMTP_HOST = "smtp.hostinger.com"
  SMTP_PASS = "!Mcommemedoc/(12)"
  SMTP_PORT = "465"
  SMTP_SECURE = "true"
  SMTP_USER = "direction@mcommemedoc.fr"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install && node --max-old-space-size=4096 ./node_modules/.bin/nuxt build"
  publish = "dist"

[context.branch-deploy]
  command = "npm install && node --max-old-space-size=4096 ./node_modules/.bin/nuxt build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[cache]
  paths = ["node_modules", "package-lock.json"]

